import os
import json
import datetime
from rss_client import collect_from_rss_feeds
from ai_client import process_with_gemini
from config import NEWS_BOT_OUTPUT_DIR
from dotenv import load_dotenv

load_dotenv()

def filter_by_time(articles, hours=24):
    """Filter articles published within the last N hours."""
    cutoff = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=hours)
    filtered = []
    for a in articles:
        pub = a.get('published')
        if pub and pub >= cutoff:
            filtered.append(a)
    return filtered

def main():
    print("=== Hybrid News Collection Start ===")
    print("1. Fetching RSS Feeds...")
    articles = collect_from_rss_feeds()
    
    # Simple Time Filter (24h)
    print("2. Filtering by Time (24h)...")
    articles = filter_by_time(articles)
    print(f"-> {len(articles)} articles remaining.")
    
    if not articles:
        print("No recent articles found.")
        return

    print("3. Processing with Gemini (Top 10 Selection)...")
    processed = process_with_gemini(articles)
    
    # Save as JSON (Legacy Format compatible with generators)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M")
    filename = f"ai_news_{timestamp}.json"
    filepath = os.path.join(NEWS_BOT_OUTPUT_DIR, filename)
    
    if not os.path.exists(NEWS_BOT_OUTPUT_DIR):
        os.makedirs(NEWS_BOT_OUTPUT_DIR)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(processed, f, indent=2, ensure_ascii=False)
        
    print(f"✅ Saved Top 10 to: {filepath}")
    
    # Also save as Markdown for visibility
    md_filename = f"ai_news_{timestamp}.md"
    md_filepath = os.path.join(NEWS_BOT_OUTPUT_DIR, md_filename)
    with open(md_filepath, 'w', encoding='utf-8') as f:
        f.write(f"# AI News Top 10 ({timestamp})\n\n")
        f.write(f"Generated by Gemini 3 Flash Preview (via RSS)\n\n")
        for i, item in enumerate(processed, 1):
            f.write(f"## {i}. {item['title_ja']}\n")
            f.write(f"- **Summary**: {item['summary_ja']}\n")
            f.write(f"- **URL**: {item['url']}\n")
            f.write(f"- **Score**: {item.get('importance_score')}\n\n")
            
    print(f"✅ Saved Markdown to: {md_filepath}")

if __name__ == "__main__":
    main()
