import os
import re
import json
import time
import datetime
from rss_client import collect_from_rss_feeds
from ai_client import process_with_gemini
from config import NEWS_BOT_OUTPUT_DIR, AI_KEYWORDS, JST
from dotenv import load_dotenv

load_dotenv()

# キーワードを正規表現パターンに事前コンパイル（大文字小文字無視）
_KEYWORD_PATTERN = re.compile(
    "|".join(re.escape(kw) for kw in AI_KEYWORDS),
    re.IGNORECASE,
)


def filter_by_time(articles, hours=24):
    """Filter articles published within the last N hours."""
    cutoff = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=hours)
    filtered = [a for a in articles if a.get('published') and a['published'] >= cutoff]
    return filtered


def score_articles(articles):
    """キーワードマッチングで関連度スコアを算出する（正規表現で高速化）"""
    scored = []
    for a in articles:
        text = (a.get('title', '') + " " + a.get('summary', ''))
        matches = _KEYWORD_PATTERN.findall(text)
        a['_relevance'] = len(matches)
        scored.append(a)

    # AI関連度 > 0 を優先、次に公開日時の降順
    scored.sort(
        key=lambda x: (
            x['_relevance'] > 0,
            x.get('published', datetime.datetime.min.replace(tzinfo=datetime.timezone.utc))
            or datetime.datetime.min.replace(tzinfo=datetime.timezone.utc),
        ),
        reverse=True,
    )
    return scored


def main():
    start = time.time()
    print("=== Hybrid News Collection Start ===")

    print("1. Fetching RSS Feeds...")
    articles = collect_from_rss_feeds()

    # Simple Time Filter (24h)
    print("2. Filtering by Time (24h)...")
    articles = filter_by_time(articles)
    print(f"-> {len(articles)} articles remaining.")

    if not articles:
        print("No recent articles found.")
        return

    print("3. Prioritizing AI-related articles...")
    scored_articles = score_articles(articles)

    # Take top 30 relevant/newest for Gemini
    input_articles = scored_articles[:30]
    print(f"-> Selected {len(input_articles)} articles for Gemini analysis (Priority: AI Relevance).")

    print("4. Processing with Gemini (AI Trend Analyst Mode)...")
    processed = process_with_gemini(input_articles)

    # Save as JSON
    timestamp = datetime.datetime.now(JST).strftime("%Y%m%d_%H%M")
    filename = f"candidates_{timestamp}.json"
    filepath = os.path.join(NEWS_BOT_OUTPUT_DIR, filename)

    os.makedirs(NEWS_BOT_OUTPUT_DIR, exist_ok=True)

    output_data = {"articles": processed}
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(output_data, f, indent=2, ensure_ascii=False)

    print(f"✅ Saved Top 10 to: {filepath}")

    # Also save as Markdown for visibility
    md_filename = f"candidates_{timestamp}.md"
    md_filepath = os.path.join(NEWS_BOT_OUTPUT_DIR, md_filename)

    now_jst = datetime.datetime.now(JST)
    updated_str = now_jst.strftime("%Y年%m月%d日 %H:%M")

    with open(md_filepath, 'w', encoding='utf-8') as f:
        f.write("# AI News Top 10\n\n")
        f.write(f"**更新日時**: {updated_str} (JST)\n\n")
        f.write("Generated by Gemini 3 Flash Preview (via RSS)\n\n")
        for i, item in enumerate(processed, 1):
            title = item.get('title_ja', item.get('title', 'No Title'))
            summary = item.get('summary_ja', item.get('summary', ''))
            category = item.get('category', '未分類')
            source = item.get('source', 'Unknown')
            url = item.get('url', '')
            f.write(f"## {i}. {title}\n\n")
            f.write(f"**カテゴリ**: {category}\n\n")
            f.write(f"{summary}\n\n")
            f.write(f"- **出典**: {source}\n")
            f.write(f"- **URL**: {url}\n\n")

    elapsed = time.time() - start
    print(f"✅ Saved Markdown to: {md_filepath}")
    print(f"⏱️  Stage 1 合計: {elapsed:.1f}秒")


if __name__ == "__main__":
    main()
